import { v4 as uuid } from 'uuid';
import { getDb } from '../db/database';
import { runMigrations } from '../db/migrate';
import dotenv from 'dotenv';
dotenv.config();

// ─── Datos ────────────────────────────────────────────────────────────────────
const TEAMS: Array<{ id: string; name: string; category: string; code: string; players: Array<{name:string;pos:string}> }> = [
  { id: 'argelia', name: 'Argelia', category: 'petardazos', code: 'ALG', players: [
    { name: 'Melvin Mastil', pos: 'portero' },
    { name: 'Aissa Mandi', pos: 'defensa' },
    { name: 'Achraf Abada', pos: 'defensa' },
    { name: 'Mohamed Amine Tougai', pos: 'defensa' },
    { name: 'Zineddine Belaid', pos: 'defensa' },
    { name: 'Ramiz Zerrouki', pos: 'medio' },
    { name: 'Riyad Mahrez', pos: 'delantero' },
    { name: 'Houssem Aouar', pos: 'medio' },
    { name: 'Amine Gouiri', pos: 'delantero' },
    { name: 'Fares Chaibi', pos: 'medio' },
    { name: 'Anis Hadj Moussa', pos: 'delantero' },
    { name: 'Nadhir Benbouali', pos: 'delantero' },
    { name: 'Jaouen Hadjam', pos: 'defensa' },
    { name: 'Hicham Boudaoui', pos: 'medio' },
    { name: 'Rayan Ait-Nouri', pos: 'defensa' },
    { name: 'Oussama Benbot', pos: 'portero' },
    { name: 'Rak Belghali', pos: 'defensa' },
    { name: 'Mohamed Amoura', pos: 'delantero' },
    { name: 'Nabil Bentaleb', pos: 'medio' },
    { name: 'Adil Boulbina', pos: 'delantero' },
    { name: 'Ramy Bensebaini', pos: 'defensa' },
    { name: 'Ibrahim Maza', pos: 'medio' },
    { name: 'Luca Zidane', pos: 'portero' },
    { name: 'Yassine Titraoui', pos: 'medio' },
    { name: 'Fares Ghedjemis', pos: 'delantero' },
    { name: 'Samir Chergui', pos: 'defensa' },
  ]},
  { id: 'argentina', name: 'Argentina', category: 'favoritos', code: 'ARG', players: [
    { name: 'Juan Musso', pos: 'portero' },
    { name: 'Leonardo Balerdi', pos: 'defensa' },
    { name: 'Nicolas Tagliafico', pos: 'defensa' },
    { name: 'Gonzalo Montiel', pos: 'defensa' },
    { name: 'Leandro Paredes', pos: 'medio' },
    { name: 'Lisandro Martinez', pos: 'defensa' },
    { name: 'Rodrigo De Paul', pos: 'medio' },
    { name: 'Valentin Barco', pos: 'medio' },
    { name: 'Julian Alvarez', pos: 'delantero' },
    { name: 'Lionel Messi', pos: 'delantero' },
    { name: 'Giovani Lo Celso', pos: 'medio' },
    { name: 'Geronimo Rulli', pos: 'portero' },
    { name: 'Cristian Romero', pos: 'defensa' },
    { name: 'Exequiel Palacios', pos: 'medio' },
    { name: 'Nico Gonzalez', pos: 'medio' },
    { name: 'Thiago Almada', pos: 'delantero' },
    { name: 'Giuliano Simeone', pos: 'delantero' },
    { name: 'Nico Paz', pos: 'delantero' },
    { name: 'Nicolas Otamendi', pos: 'defensa' },
    { name: 'Alexis Mac Allister', pos: 'medio' },
    { name: 'Jose Manuel Lopez', pos: 'delantero' },
    { name: 'Lautaro Martinez', pos: 'delantero' },
    { name: 'Emiliano Martinez', pos: 'portero' },
    { name: 'Enzo Fernandez', pos: 'medio' },
    { name: 'Facundo Medina', pos: 'defensa' },
    { name: 'Nahuel Molina', pos: 'defensa' },
  ]},
  { id: 'australia', name: 'Australia', category: 'sorpresas', code: 'AUS', players: [
    { name: 'Mathew Ryan', pos: 'portero' },
    { name: 'Milos Degenek', pos: 'defensa' },
    { name: 'Alessandro Circati', pos: 'defensa' },
    { name: 'Jacob Italiano', pos: 'defensa' },
    { name: 'Jordan Bos', pos: 'defensa' },
    { name: 'Jason Geria', pos: 'defensa' },
    { name: 'Mathew Leckie', pos: 'delantero' },
    { name: 'Connor Metcalfe', pos: 'medio' },
    { name: 'Mohamed Toure', pos: 'delantero' },
    { name: 'Ajdin Hrustic', pos: 'delantero' },
    { name: 'Awer Mabil', pos: 'delantero' },
    { name: 'Paul Izzo', pos: 'portero' },
    { name: 'Aiden Oneill', pos: 'medio' },
    { name: 'Cameron Devlin', pos: 'medio' },
    { name: 'Kai Trewin', pos: 'defensa' },
    { name: 'Aziz Behich', pos: 'defensa' },
    { name: 'Nestory Irankunda', pos: 'delantero' },
    { name: 'Patrick Beach', pos: 'portero' },
    { name: 'Harry Souttar', pos: 'defensa' },
    { name: 'Cristian Volpato', pos: 'delantero' },
    { name: 'Cameron Burgess', pos: 'defensa' },
    { name: 'Jackson Irvine', pos: 'medio' },
    { name: 'Nishan Velupillay', pos: 'delantero' },
    { name: 'Paul Okon-Engstler', pos: 'medio' },
    { name: 'Lucas Herrington', pos: 'defensa' },
    { name: 'Tete Yengi', pos: 'delantero' },
  ]},
  { id: 'austria', name: 'Austria', category: 'sorpresas', code: 'AUT', players: [
    { name: 'Alexander Schlager', pos: 'portero' },
    { name: 'David Affengruber', pos: 'defensa' },
    { name: 'Kevin Danso', pos: 'defensa' },
    { name: 'Xaver Schlager', pos: 'medio' },
    { name: 'Stefan Posch', pos: 'defensa' },
    { name: 'Nicolas Seiwald', pos: 'medio' },
    { name: 'Marko Arnautovic', pos: 'delantero' },
    { name: 'David Alaba', pos: 'defensa' },
    { name: 'Marcel Sabitzer', pos: 'medio' },
    { name: 'Florian Grillitsch', pos: 'medio' },
    { name: 'Michael Gregoritsch', pos: 'delantero' },
    { name: 'Florian Wiegele', pos: 'portero' },
    { name: 'Patrick Pentz', pos: 'portero' },
    { name: 'Sasa Kalajdzic', pos: 'delantero' },
    { name: 'Philipp Lienhart', pos: 'defensa' },
    { name: 'Phillip Mwene', pos: 'defensa' },
    { name: 'Carney Chukwuemeka', pos: 'medio' },
    { name: 'Romano Schmid', pos: 'medio' },
    { name: 'Christoph Baumgartner', pos: 'medio' },
    { name: 'Konrad Laimer', pos: 'medio' },
    { name: 'Patrick Wimmer', pos: 'delantero' },
    { name: 'Alexander Prass', pos: 'medio' },
    { name: 'Marco Friedl', pos: 'defensa' },
    { name: 'Paul Wanner', pos: 'medio' },
    { name: 'Michael Svoboda', pos: 'defensa' },
    { name: 'Alessandro Schoepf', pos: 'medio' },
  ]},
  { id: 'belgica', name: 'Bélgica', category: 'favoritos', code: 'BEL', players: [
    { name: 'Thibaut Courtois', pos: 'portero' },
    { name: 'Zeno Debast', pos: 'defensa' },
    { name: 'Arthur Theate', pos: 'defensa' },
    { name: 'Brandon Mechele', pos: 'defensa' },
    { name: 'Maxim De Cuyper', pos: 'defensa' },
    { name: 'Axel Witsel', pos: 'medio' },
    { name: 'Kevin De Bruyne', pos: 'medio' },
    { name: 'Youri Tielemans', pos: 'medio' },
    { name: 'Romelu Lukaku', pos: 'delantero' },
    { name: 'Leandro Trossard', pos: 'delantero' },
    { name: 'Jeremy Doku', pos: 'delantero' },
    { name: 'Senne Lammens', pos: 'portero' },
    { name: 'Mike Penders', pos: 'portero' },
    { name: 'Dodi Lukebakio', pos: 'delantero' },
    { name: 'Thomas Meunier', pos: 'defensa' },
    { name: 'Koni De Winter', pos: 'defensa' },
    { name: 'Charles De Ketelaere', pos: 'delantero' },
    { name: 'Joaquin Seys', pos: 'defensa' },
    { name: 'Diego Moreira', pos: 'medio' },
    { name: 'Hans Vanaken', pos: 'medio' },
    { name: 'Timothy Castagne', pos: 'defensa' },
    { name: 'Alexis Saelemaekers', pos: 'medio' },
    { name: 'Nicolas Raskin', pos: 'medio' },
    { name: 'Amadou Onana', pos: 'medio' },
    { name: 'Nathan Ngoy', pos: 'defensa' },
    { name: 'Matias Fernandez-Pardo', pos: 'delantero' },
  ]},
  { id: 'bosnia', name: 'Bosnia y Herz.', category: 'caca', code: 'BIH', players: [
    { name: 'Nikola Vasilj', pos: 'portero' },
    { name: 'Nihad Mujakic', pos: 'defensa' },
    { name: 'Dennis Hadzikadunic', pos: 'defensa' },
    { name: 'Tarik Muharemovic', pos: 'defensa' },
    { name: 'Sead Kolasinac', pos: 'defensa' },
    { name: 'Benjamin Tahirovic', pos: 'medio' },
    { name: 'Amar Dedic', pos: 'defensa' },
    { name: 'Armin Gigovic', pos: 'medio' },
    { name: 'Samed Bazdar', pos: 'delantero' },
    { name: 'Ermedin Demirovic', pos: 'delantero' },
    { name: 'Edin Dzeko', pos: 'delantero' },
    { name: 'Mladen Jurkas', pos: 'portero' },
    { name: 'Ivan Basic', pos: 'medio' },
    { name: 'Ivan Sunjic', pos: 'medio' },
    { name: 'Amar Memic', pos: 'medio' },
    { name: 'Amir Hadziahmetovic', pos: 'medio' },
    { name: 'Dzenis Burnic', pos: 'medio' },
    { name: 'Nikola Katic', pos: 'defensa' },
    { name: 'Kerim Alajbegovic', pos: 'delantero' },
    { name: 'Esmir Bajraktarevic', pos: 'delantero' },
    { name: 'Stjepan Radeljic', pos: 'defensa' },
    { name: 'Martin Zlomislic', pos: 'portero' },
    { name: 'Haris Tabakovic', pos: 'delantero' },
    { name: 'Nidal Celik', pos: 'defensa' },
    { name: 'Jovo Lukic', pos: 'delantero' },
    { name: 'Ermin Mahmic', pos: 'medio' },
  ]},
  { id: 'brasil', name: 'Brasil', category: 'favoritos', code: 'BRA', players: [
    { name: 'Alisson', pos: 'portero' },
    { name: 'Wesley', pos: 'defensa' },
    { name: 'Gabriel Magalhaes', pos: 'defensa' },
    { name: 'Marquinhos', pos: 'defensa' },
    { name: 'Casemiro', pos: 'medio' },
    { name: 'Alex Sandro', pos: 'defensa' },
    { name: 'Vinicius Junior', pos: 'delantero' },
    { name: 'Bruno Guimaraes', pos: 'medio' },
    { name: 'Matheus Cunha', pos: 'delantero' },
    { name: 'Neymar Jr', pos: 'delantero' },
    { name: 'Raphinha', pos: 'delantero' },
    { name: 'Weverton', pos: 'portero' },
    { name: 'Danilo', pos: 'defensa' },
    { name: 'Bremer', pos: 'defensa' },
    { name: 'Leo Pereira', pos: 'defensa' },
    { name: 'Douglas Santos', pos: 'defensa' },
    { name: 'Fabinho', pos: 'medio' },
    { name: 'Danilo Santos', pos: 'medio' },
    { name: 'Endrick', pos: 'delantero' },
    { name: 'Lucas Paqueta', pos: 'medio' },
    { name: 'Luiz Henrique', pos: 'delantero' },
    { name: 'Gabriel Martinelli', pos: 'delantero' },
    { name: 'Ederson', pos: 'portero' },
    { name: 'Roger Ibanez', pos: 'defensa' },
    { name: 'Igor Thiago', pos: 'delantero' },
    { name: 'Rayan', pos: 'delantero' },
  ]},
  { id: 'cabo-verde', name: 'Cabo Verde', category: 'caca', code: 'CPV', players: [
    { name: 'Vozinha', pos: 'portero' },
    { name: 'Stopira', pos: 'defensa' },
    { name: 'Diney Borges', pos: 'defensa' },
    { name: 'Pico Lopes', pos: 'defensa' },
    { name: 'Logan Costa', pos: 'defensa' },
    { name: 'Kevin Pina', pos: 'medio' },
    { name: 'Jovane Cabral', pos: 'medio' },
    { name: 'Joao Paulo', pos: 'medio' },
    { name: 'Gilson Benchimol', pos: 'delantero' },
    { name: 'Jamiro Monteiro', pos: 'medio' },
    { name: 'Garry Rodrigues', pos: 'medio' },
    { name: 'Marcio Rosa', pos: 'portero' },
    { name: 'Sidny Lopes Cabral', pos: 'defensa' },
    { name: 'Deroy Duarte', pos: 'medio' },
    { name: 'Laros Duarte', pos: 'medio' },
    { name: 'Yannick Semedo', pos: 'medio' },
    { name: 'Willy Semedo', pos: 'medio' },
    { name: 'Telmo Arcanjo', pos: 'medio' },
    { name: 'Dailon Livramento', pos: 'delantero' },
    { name: 'Ryan Mendes', pos: 'delantero' },
    { name: 'Nuno Da Costa', pos: 'medio' },
    { name: 'Steven Moreira', pos: 'defensa' },
    { name: 'Cj Dos Santos', pos: 'portero' },
    { name: 'Wagner Pina', pos: 'defensa' },
    { name: 'Kelvin Pires', pos: 'defensa' },
    { name: 'Helio Varela', pos: 'medio' },
  ]},
  { id: 'canada', name: 'Canadá', category: 'petardazos', code: 'CAN', players: [
    { name: 'St. Clair Dayne', pos: 'portero' },
    { name: 'Alistair Johnston', pos: 'defensa' },
    { name: 'Ale Jones', pos: 'defensa' },
    { name: 'Luc De Fougerolles', pos: 'defensa' },
    { name: 'Joel Waterman', pos: 'defensa' },
    { name: 'Mathieu Choiniere', pos: 'medio' },
    { name: 'Stephen Eustaquio', pos: 'medio' },
    { name: 'Ismael Kone', pos: 'medio' },
    { name: 'Cyle Larin', pos: 'delantero' },
    { name: 'Jonathan David', pos: 'delantero' },
    { name: 'Liam Millar', pos: 'medio' },
    { name: 'Tani Oluwaseyi', pos: 'delantero' },
    { name: 'Derek Cornelius', pos: 'defensa' },
    { name: 'Jacob Shaffelburg', pos: 'medio' },
    { name: 'Moise Bombito', pos: 'defensa' },
    { name: 'Maxime Crepeau', pos: 'portero' },
    { name: 'Tajon Buchanan', pos: 'delantero' },
    { name: 'Owen Goodman', pos: 'portero' },
    { name: 'Alphonso Davies', pos: 'defensa' },
    { name: 'Ali Ahmed', pos: 'delantero' },
    { name: 'Jonathan Osorio', pos: 'medio' },
    { name: 'Richie Laryea', pos: 'defensa' },
    { name: 'Niko Sigur', pos: 'defensa' },
    { name: 'Promise David', pos: 'delantero' },
    { name: 'Nathan Saliba', pos: 'medio' },
    { name: 'Marcelo Flores', pos: 'medio' },
  ]},
  { id: 'colombia', name: 'Colombia', category: 'sorpresas', code: 'COL', players: [
    { name: 'David Ospina', pos: 'portero' },
    { name: 'Daniel Munoz', pos: 'defensa' },
    { name: 'Jhon Lucumi', pos: 'defensa' },
    { name: 'Santiago Arias', pos: 'defensa' },
    { name: 'Kevin Castano', pos: 'medio' },
    { name: 'Richard Rios', pos: 'medio' },
    { name: 'Luis Diaz', pos: 'delantero' },
    { name: 'Jorge Carrascal', pos: 'medio' },
    { name: 'Jhon Cordoba', pos: 'delantero' },
    { name: 'James Rodriguez', pos: 'medio' },
    { name: 'Jhon Arias', pos: 'medio' },
    { name: 'Camilo Vargas', pos: 'portero' },
    { name: 'Yerry Mina', pos: 'defensa' },
    { name: 'Gustavo Puerta', pos: 'defensa' },
    { name: 'Juan Portilla', pos: 'medio' },
    { name: 'Jefferson Lerma', pos: 'medio' },
    { name: 'Johan Mojica', pos: 'defensa' },
    { name: 'Willer Ditta', pos: 'defensa' },
    { name: 'Cucho Hernandez', pos: 'delantero' },
    { name: 'Juan Quintero', pos: 'medio' },
    { name: 'Leandro Campaz', pos: 'delantero' },
    { name: 'Deiver Machado', pos: 'defensa' },
    { name: 'Davinson Sanchez', pos: 'defensa' },
    { name: 'Alvaro Montero', pos: 'portero' },
    { name: 'Luis Suarez', pos: 'delantero' },
    { name: 'Andres Gomez', pos: 'delantero' },
  ]},
  { id: 'rd-congo', name: 'RD Congo', category: 'petardazos', code: 'COD', players: [
    { name: 'Lionel Mpasi', pos: 'portero' },
    { name: 'Aaron Wan-Bissaka', pos: 'defensa' },
    { name: 'Steve Kapuadi', pos: 'defensa' },
    { name: 'Axel Tuanzebe', pos: 'defensa' },
    { name: 'Dylan Batubinsika', pos: 'defensa' },
    { name: 'Ngalayel Mukau', pos: 'medio' },
    { name: 'Nathanael Mbuku', pos: 'medio' },
    { name: 'Samuel Moutoussamy', pos: 'medio' },
    { name: 'Brian Cipenga', pos: 'delantero' },
    { name: 'Theo Bongonda', pos: 'medio' },
    { name: 'Gael Kakuta', pos: 'delantero' },
    { name: 'Joris Kayembe', pos: 'defensa' },
    { name: 'Meschack Elia', pos: 'delantero' },
    { name: 'Noah Sadiki', pos: 'medio' },
    { name: 'Aaron Tshibola', pos: 'medio' },
    { name: 'Timothy Fayulu', pos: 'portero' },
    { name: 'Cedric Bakambu', pos: 'delantero' },
    { name: 'Charles Pickel', pos: 'medio' },
    { name: 'Fiston Mayele', pos: 'delantero' },
    { name: 'Yoane Wissa', pos: 'delantero' },
    { name: 'Matthieu Epolo', pos: 'portero' },
    { name: 'Chancel Mbemba', pos: 'defensa' },
    { name: 'Simon Banza', pos: 'delantero' },
    { name: 'Gedeon Kalulu', pos: 'defensa' },
    { name: 'Edo Kayembe', pos: 'medio' },
    { name: 'Arthur Masuaku', pos: 'defensa' },
  ]},
  { id: 'costa-de-marfil', name: 'Costa de Marfil', category: 'petardazos', code: 'CIV', players: [
    { name: 'Yahia Fofana', pos: 'portero' },
    { name: 'Ousmane Diomande', pos: 'defensa' },
    { name: 'Ghislain Konan', pos: 'defensa' },
    { name: 'Jean Michael Seri', pos: 'medio' },
    { name: 'Wilfried Singo', pos: 'defensa' },
    { name: 'Seko Fofana', pos: 'medio' },
    { name: 'Odilon Kossounou', pos: 'defensa' },
    { name: 'Franck Kessie', pos: 'medio' },
    { name: 'Ange-Yoan Bonny', pos: 'delantero' },
    { name: 'Simon Adingra', pos: 'delantero' },
    { name: 'Yan Diomande', pos: 'delantero' },
    { name: 'Elye Wahi', pos: 'delantero' },
    { name: 'Christopher Operi', pos: 'defensa' },
    { name: 'Oumar Diakite', pos: 'delantero' },
    { name: 'Amad Diallo', pos: 'delantero' },
    { name: 'Mohamed Kone', pos: 'portero' },
    { name: 'Guela Doue', pos: 'defensa' },
    { name: 'Ibrahim Sangare', pos: 'medio' },
    { name: 'Nicolas Pepe', pos: 'delantero' },
    { name: 'Yahia', pos: 'defensa' },
    { name: 'Ousmane', pos: 'defensa' },
    { name: 'N\'Clomande Ghislain', pos: 'delantero' },
    { name: 'Jean Michael', pos: 'portero' },
    { name: 'Wilfried Stephane', pos: 'delantero' },
    { name: 'Seko Mohamed', pos: 'medio' },
    { name: 'Kouakou Odilon Dorgeless', pos: 'medio' },
  ]},
  { id: 'croacia', name: 'Croacia', category: 'sorpresas', code: 'CRO', players: [
    { name: 'Dominik Livakovic', pos: 'portero' },
    { name: 'Josip Stanisic', pos: 'defensa' },
    { name: 'Marin Pongracic', pos: 'defensa' },
    { name: 'Josko Gvardiol', pos: 'defensa' },
    { name: 'Duje Caleta-Car', pos: 'defensa' },
    { name: 'Josip Sutalo', pos: 'defensa' },
    { name: 'Nikola Moro', pos: 'medio' },
    { name: 'Mateo Kovacic', pos: 'medio' },
    { name: 'Andrej Kramaric', pos: 'delantero' },
    { name: 'Luka Modric', pos: 'medio' },
    { name: 'Ante Budimir', pos: 'delantero' },
    { name: 'Ivor Pandur', pos: 'portero' },
    { name: 'Nikola Vlasic', pos: 'medio' },
    { name: 'Ivan Perisic', pos: 'delantero' },
    { name: 'Mario Pasalic', pos: 'medio' },
    { name: 'Martin Baturina', pos: 'medio' },
    { name: 'Petar Sucic', pos: 'medio' },
    { name: 'Kristijan Jakic', pos: 'defensa' },
    { name: 'Toni Fruk', pos: 'medio' },
    { name: 'Igor Matanovic', pos: 'delantero' },
    { name: 'Luka Sucic', pos: 'medio' },
    { name: 'Luka Vuskovic', pos: 'defensa' },
    { name: 'Dominik Kotarski', pos: 'portero' },
    { name: 'Marco Pasalic', pos: 'delantero' },
    { name: 'Martin Erlic', pos: 'defensa' },
    { name: 'Petar Musa', pos: 'delantero' },
  ]},
  { id: 'curazao', name: 'Curazao', category: 'caca', code: 'CUW', players: [
    { name: 'Eloy Room', pos: 'portero' },
    { name: 'Shurandy Sambo', pos: 'defensa' },
    { name: 'Jurien Gaari', pos: 'defensa' },
    { name: 'Roshon Van Eijma', pos: 'defensa' },
    { name: 'Sherel Floranus', pos: 'defensa' },
    { name: 'Godfried Roemeratoe', pos: 'medio' },
    { name: 'Juninho Bacuna', pos: 'medio' },
    { name: 'Livano Comenencia', pos: 'medio' },
    { name: 'Juergen Locadia', pos: 'delantero' },
    { name: 'Leandro Bacuna', pos: 'medio' },
    { name: 'Jeremy Antonisse', pos: 'delantero' },
    { name: 'Sontje Hansen', pos: 'delantero' },
    { name: 'Tyrese Noslin', pos: 'delantero' },
    { name: 'Kenji Gorre', pos: 'delantero' },
    { name: 'Arjany Martha', pos: 'medio' },
    { name: 'Jearl Margaritha', pos: 'delantero' },
    { name: 'Brandley Kuwas', pos: 'delantero' },
    { name: 'Armando Obispo', pos: 'defensa' },
    { name: 'Gervane Kastaneer', pos: 'delantero' },
    { name: 'Joshua Brenet', pos: 'defensa' },
    { name: 'Tahith Chong', pos: 'medio' },
    { name: 'Kevin Felida', pos: 'medio' },
    { name: 'Riechedly Bazoer', pos: 'defensa' },
    { name: 'Deveron Fonville', pos: 'defensa' },
    { name: 'Tyrick Bodak', pos: 'portero' },
    { name: 'Trevor Doornbusch', pos: 'portero' },
  ]},
  { id: 'rep-checa', name: 'Rep. Checa', category: 'petardazos', code: 'CZE', players: [
    { name: 'Matej Kovar', pos: 'portero' },
    { name: 'David Zima', pos: 'defensa' },
    { name: 'Tomas Holes', pos: 'defensa' },
    { name: 'Robin Hranac', pos: 'defensa' },
    { name: 'Vladimir Coufal', pos: 'defensa' },
    { name: 'Stepan Chaloupek', pos: 'defensa' },
    { name: 'Ladislav Krejci', pos: 'defensa' },
    { name: 'Vladimir Darida', pos: 'medio' },
    { name: 'Adam Hlozek', pos: 'delantero' },
    { name: 'Patrik Schick', pos: 'delantero' },
    { name: 'Jan Kuchta', pos: 'delantero' },
    { name: 'Lukas Cerv', pos: 'medio' },
    { name: 'Mojmir Chytil', pos: 'delantero' },
    { name: 'David Jurasek', pos: 'defensa' },
    { name: 'Pavel Sulc', pos: 'delantero' },
    { name: 'Jindrich Stanek', pos: 'portero' },
    { name: 'Lukas Provod', pos: 'medio' },
    { name: 'Michal Sadilek', pos: 'medio' },
    { name: 'Tomas Chory', pos: 'delantero' },
    { name: 'Jaroslav Zeleny', pos: 'defensa' },
    { name: 'David Doudera', pos: 'defensa' },
    { name: 'Tomas Soucek', pos: 'medio' },
    { name: 'Lukas Hornicek', pos: 'portero' },
    { name: 'Alexandr Sojka', pos: 'medio' },
    { name: 'Hugo Sochurek', pos: 'medio' },
    { name: 'Denis Visinsky', pos: 'delantero' },
  ]},
  { id: 'ecuador', name: 'Ecuador', category: 'sorpresas', code: 'ECU', players: [
    { name: 'Hernan Galindez', pos: 'portero' },
    { name: 'Felix Torres', pos: 'defensa' },
    { name: 'Piero Hincapie', pos: 'defensa' },
    { name: 'Joel Ordonez', pos: 'defensa' },
    { name: 'Jordy Alcivar', pos: 'medio' },
    { name: 'Willian Pacho', pos: 'defensa' },
    { name: 'Pervis Estupinan', pos: 'defensa' },
    { name: 'Anthony Valencia', pos: 'medio' },
    { name: 'John Yeboah', pos: 'delantero' },
    { name: 'Kendry Paez', pos: 'medio' },
    { name: 'Kevin Rodriguez', pos: 'delantero' },
    { name: 'Moises Ramirez', pos: 'portero' },
    { name: 'Enner Valencia', pos: 'delantero' },
    { name: 'Alan Minda', pos: 'medio' },
    { name: 'Pedro Vite', pos: 'medio' },
    { name: 'Jordy Caicedo', pos: 'delantero' },
    { name: 'Angelo Preciado', pos: 'defensa' },
    { name: 'Denil Castillo', pos: 'medio' },
    { name: 'Gonzalo Plata', pos: 'delantero' },
    { name: 'Nilson Angulo', pos: 'delantero' },
    { name: 'Alan Franco', pos: 'medio' },
    { name: 'Gonzalo Valle', pos: 'portero' },
    { name: 'Moises Caicedo', pos: 'medio' },
    { name: 'Jeremy Arevalo', pos: 'delantero' },
    { name: 'Jackson Porozo', pos: 'defensa' },
    { name: 'Yaimar Medina', pos: 'defensa' },
  ]},
  { id: 'egipto', name: 'Egipto', category: 'petardazos', code: 'EGY', players: [
    { name: 'Yasser Ibrahim', pos: 'portero' },
    { name: 'Mohamed Hany', pos: 'defensa' },
    { name: 'Hossam Abdelmaguid', pos: 'defensa' },
    { name: 'Ramy Rabia', pos: 'defensa' },
    { name: 'Yasser Ahmed Ibrahim', pos: 'defensa' },
    { name: 'Mohamed Hany Gamal', pos: 'defensa' },
    { name: 'Hossam Abdelmegeed Abdelsalam', pos: 'delantero' },
    { name: 'Ramy Hisham Abdelaziz Moustafa', pos: 'medio' },
    { name: 'Mohamed Abdelmoneim', pos: 'delantero' },
    { name: 'Mohamed Abdelmoneim Elsayed M', pos: 'delantero' },
    { name: 'Trezeguet', pos: 'medio' },
    { name: 'Emam Ashour', pos: 'delantero' },
    { name: 'Hamza Abdelkarim', pos: 'defensa' },
    { name: 'Mohamed Salah', pos: 'medio' },
    { name: 'Mostafa Zico', pos: 'defensa' },
    { name: 'Haissem Hassan', pos: 'portero' },
    { name: 'Ahmed Fatouh', pos: 'medio' },
    { name: 'Hamdy Fathy', pos: 'medio' },
    { name: 'Karim Hafez', pos: 'medio' },
    { name: 'Mahdy Soliman', pos: 'delantero' },
    { name: 'Mohanad Lashin', pos: 'medio' },
    { name: 'Nabil Donga', pos: 'delantero' },
    { name: 'Marawan Attia', pos: 'portero' },
    { name: 'Ibrahim Adel', pos: 'defensa' },
    { name: 'Mahmoud Saber', pos: 'delantero' },
    { name: 'Omar Marmoush', pos: 'portero' },
  ]},
  { id: 'inglaterra', name: 'Inglaterra', category: 'favoritos', code: 'ENG', players: [
    { name: 'Jordan Pickford', pos: 'portero' },
    { name: 'Ezri Konsa', pos: 'defensa' },
    { name: 'Nico Oreilly', pos: 'defensa' },
    { name: 'Declan Rice', pos: 'medio' },
    { name: 'John Stones', pos: 'defensa' },
    { name: 'Marc Guehi', pos: 'defensa' },
    { name: 'Bukayo Saka', pos: 'delantero' },
    { name: 'Elliot Anderson', pos: 'medio' },
    { name: 'Harry Kane', pos: 'delantero' },
    { name: 'Jude Bellingham', pos: 'medio' },
    { name: 'Marcus Rashford', pos: 'delantero' },
    { name: 'Tino Livramento', pos: 'defensa' },
    { name: 'Dean Henderson', pos: 'portero' },
    { name: 'Jordan Henderson', pos: 'medio' },
    { name: 'Dan Burn', pos: 'defensa' },
    { name: 'Kobbie Mainoo', pos: 'medio' },
    { name: 'Morgan Rogers', pos: 'medio' },
    { name: 'Anthony Gordon', pos: 'delantero' },
    { name: 'Ollie Watkins', pos: 'delantero' },
    { name: 'Noni Madueke', pos: 'delantero' },
    { name: 'Eberechi Eze', pos: 'medio' },
    { name: 'Ivan Toney', pos: 'delantero' },
    { name: 'James Trafford', pos: 'portero' },
    { name: 'Reece James', pos: 'defensa' },
    { name: 'Djed Spence', pos: 'defensa' },
    { name: 'Jarell Quansah', pos: 'defensa' },
  ]},
  { id: 'francia', name: 'Francia', category: 'favoritos', code: 'FRA', players: [
    { name: 'Brice Samba', pos: 'portero' },
    { name: 'Malo Gusto', pos: 'defensa' },
    { name: 'Lucas Digne', pos: 'defensa' },
    { name: 'Brice Lauriche', pos: 'defensa' },
    { name: 'Malo Arthur', pos: 'defensa' },
    { name: 'Lucas', pos: 'medio' },
    { name: 'Samba', pos: 'delantero' },
    { name: 'Gusto', pos: 'medio' },
    { name: 'Digne', pos: 'delantero' },
    { name: 'Samba', pos: 'delantero' },
    { name: 'Gusto', pos: 'delantero' },
    { name: 'Digne', pos: 'delantero' },
    { name: 'Dayot Upamecano', pos: 'medio' },
    { name: 'Dayotchanculle Oswald', pos: 'medio' },
    { name: 'Upamecano', pos: 'defensa' },
    { name: 'Upamecano', pos: 'portero' },
    { name: 'Jules Kounde', pos: 'defensa' },
    { name: 'Manu Kone', pos: 'medio' },
    { name: 'Ousmane Dembele', pos: 'defensa' },
    { name: 'Aurelien Tchouameni', pos: 'delantero' },
    { name: 'Marcus Thuram', pos: 'defensa' },
    { name: 'Kylian Mbappe', pos: 'delantero' },
    { name: 'Michael Olise', pos: 'portero' },
    { name: 'Bradley Barcola', pos: 'medio' },
    { name: 'Ngolo Kante', pos: 'medio' },
    { name: 'Adrien Rabiot', pos: 'defensa' },
  ]},
  { id: 'alemania', name: 'Alemania', category: 'favoritos', code: 'GER', players: [
    { name: 'Manuel Neuer', pos: 'portero' },
    { name: 'Antonio Ruediger', pos: 'defensa' },
    { name: 'Waldemar Anton', pos: 'defensa' },
    { name: 'Jonathan Tah', pos: 'defensa' },
    { name: 'Aleksandar Pavlovic', pos: 'medio' },
    { name: 'Joshua Kimmich', pos: 'defensa' },
    { name: 'Kai Havertz', pos: 'delantero' },
    { name: 'Leon Goretzka', pos: 'medio' },
    { name: 'Jamie Leweling', pos: 'medio' },
    { name: 'Jamal Musiala', pos: 'medio' },
    { name: 'Nick Woltemade', pos: 'delantero' },
    { name: 'Oliver Baumann', pos: 'portero' },
    { name: 'Pascal Gross', pos: 'medio' },
    { name: 'Maximilian Beier', pos: 'delantero' },
    { name: 'Nico Schlotterbeck', pos: 'defensa' },
    { name: 'Angelo Stiller', pos: 'medio' },
    { name: 'Florian Wirtz', pos: 'medio' },
    { name: 'Nathaniel Brown', pos: 'defensa' },
    { name: 'Leroy Sane', pos: 'medio' },
    { name: 'Nadiem Amiri', pos: 'medio' },
    { name: 'Alexander Nuebel', pos: 'portero' },
    { name: 'David Raum', pos: 'defensa' },
    { name: 'Felix Nmecha', pos: 'medio' },
    { name: 'Malick Thiaw', pos: 'defensa' },
    { name: 'Lennart Karl', pos: 'medio' },
    { name: 'Deniz Undav', pos: 'delantero' },
  ]},
  { id: 'ghana', name: 'Ghana', category: 'caca', code: 'GHA', players: [
    { name: 'Antoine Semenyo', pos: 'portero' },
    { name: 'Joseph Anang', pos: 'defensa' },
    { name: 'Christopher Bonsu Baah', pos: 'medio' },
    { name: 'Gideon Mensah', pos: 'defensa' },
    { name: 'Elisha Owusu', pos: 'medio' },
    { name: 'Benjamin Asare', pos: 'defensa' },
    { name: 'Baba Rahman', pos: 'delantero' },
    { name: 'Jerome Opoku', pos: 'medio' },
    { name: 'Inaki Williams', pos: 'delantero' },
    { name: 'Augustine Boakye', pos: 'delantero' },
    { name: 'Kojo Peprah Oppong', pos: 'medio' },
    { name: 'Kamaldeen Sulemana', pos: 'portero' },
    { name: 'Derrick Luckassen', pos: 'delantero' },
    { name: 'Ernest Nuamah', pos: 'defensa' },
    { name: 'Prince Adu', pos: 'medio' },
    { name: 'Marvin Senaya', pos: 'portero' },
    { name: 'Antoine Serlom', pos: 'defensa' },
    { name: 'Joseph Tetteh', pos: 'defensa' },
    { name: 'Christopher Bonsu', pos: 'delantero' },
    { name: 'Gideon', pos: 'medio' },
    { name: 'Elisha', pos: 'defensa' },
    { name: 'Benjamin', pos: 'delantero' },
    { name: 'Abdul Rahaman', pos: 'defensa' },
    { name: 'Jerome', pos: 'delantero' },
    { name: 'Inaki', pos: 'delantero' },
    { name: 'Augustine', pos: 'defensa' },
  ]},
  { id: 'haiti', name: 'Haití', category: 'caca', code: 'HAI', players: [
    { name: 'Johny Placide', pos: 'portero' },
    { name: 'Carlens Arcus', pos: 'defensa' },
    { name: 'Keeto Thermoncy', pos: 'defensa' },
    { name: 'Ricardo Ade', pos: 'defensa' },
    { name: 'Hannes Delcroix', pos: 'defensa' },
    { name: 'Carl Sainte', pos: 'medio' },
    { name: 'Derrick Etienne', pos: 'delantero' },
    { name: 'Martin Experience', pos: 'defensa' },
    { name: 'Duckens Nazon', pos: 'delantero' },
    { name: 'Jean-Ricner Bellegarde', pos: 'medio' },
    { name: 'Louicius Deedson', pos: 'delantero' },
    { name: 'Alexandre Pierre', pos: 'portero' },
    { name: 'Markhus Lacroix', pos: 'defensa' },
    { name: 'Leverton Pierre', pos: 'medio' },
    { name: 'Ruben Providence', pos: 'delantero' },
    { name: 'Lenny Joseph', pos: 'delantero' },
    { name: 'Danley Jean Jacques', pos: 'medio' },
    { name: 'Wilson Isidor', pos: 'delantero' },
    { name: 'Yassin Fortune', pos: 'delantero' },
    { name: 'Frantzdy Pierrot', pos: 'delantero' },
    { name: 'Josue Casimir', pos: 'delantero' },
    { name: 'Jean-Kevin Duverne', pos: 'defensa' },
    { name: 'Josue Duverger', pos: 'portero' },
    { name: 'Wilguens Paugain', pos: 'defensa' },
    { name: 'Dominique Simon', pos: 'medio' },
    { name: 'Woodensky Pierre', pos: 'medio' },
  ]},
  { id: 'iran', name: 'Irán', category: 'sorpresas', code: 'IRN', players: [
    { name: 'Alireza Beiranvand', pos: 'portero' },
    { name: 'Saleh Hardani', pos: 'defensa' },
    { name: 'Ehsan Hajisafi', pos: 'defensa' },
    { name: 'Shoja Khalilzadeh', pos: 'defensa' },
    { name: 'Milad Mohammadi', pos: 'defensa' },
    { name: 'Saeid Ezatolahi', pos: 'medio' },
    { name: 'Alireza Jahanbakhsh', pos: 'medio' },
    { name: 'Mohammad Mohebbi', pos: 'medio' },
    { name: 'Mehdi Taremi', pos: 'delantero' },
    { name: 'Mehdi Ghayedi', pos: 'delantero' },
    { name: 'Ali Alipour', pos: 'delantero' },
    { name: 'Payam Niazmand', pos: 'portero' },
    { name: 'Hossein Kanani', pos: 'defensa' },
    { name: 'Saman Ghoddos', pos: 'medio' },
    { name: 'Roozbeh Cheshmi', pos: 'medio' },
    { name: 'Mehdi Torabi', pos: 'medio' },
    { name: 'Arya Yousefi', pos: 'defensa' },
    { name: 'Amirhossein Hosseinzadeh', pos: 'delantero' },
    { name: 'Ali Nemati', pos: 'defensa' },
    { name: 'Shahriyar Moghanloo', pos: 'delantero' },
    { name: 'Mohammad Ghorbani', pos: 'medio' },
    { name: 'Hossein Hosseini', pos: 'portero' },
    { name: 'Ramin Rezaeian', pos: 'defensa' },
    { name: 'Dennis Dargahi', pos: 'delantero' },
    { name: 'Danial Iri', pos: 'defensa' },
    { name: 'Ali Reza', pos: 'medio' },
  ]},
  { id: 'irak', name: 'Irak', category: 'petardazos', code: 'IRQ', players: [
    { name: 'Fahad Talib', pos: 'portero' },
    { name: 'Rebin Ghareeb', pos: 'defensa' },
    { name: 'Hussein Ali', pos: 'defensa' },
    { name: 'Zaid Tahseen', pos: 'defensa' },
    { name: 'Akam Hashim', pos: 'defensa' },
    { name: 'Munaf Younus', pos: 'defensa' },
    { name: 'Youssef Amyn', pos: 'medio' },
    { name: 'Ibrahim Bayesh', pos: 'medio' },
    { name: 'Ali Alhamadi', pos: 'delantero' },
    { name: 'Mohanad Ali', pos: 'delantero' },
    { name: 'Ahmed Qasim', pos: 'delantero' },
    { name: 'Jalal Hassan', pos: 'portero' },
    { name: 'Ali Yousif', pos: 'delantero' },
    { name: 'Zidane Iqbal', pos: 'medio' },
    { name: 'Ahmed Yahya', pos: 'defensa' },
    { name: 'Amir Alammari', pos: 'medio' },
    { name: 'Ali Jasim', pos: 'delantero' },
    { name: 'Aymen Hussein', pos: 'delantero' },
    { name: 'Kevin Yakob', pos: 'medio' },
    { name: 'Aimar Sher', pos: 'medio' },
    { name: 'Marko Farji', pos: 'delantero' },
    { name: 'Ahmed Basil', pos: 'portero' },
    { name: 'Merchas Doski', pos: 'defensa' },
    { name: 'Zaid Ismael', pos: 'medio' },
    { name: 'Mustafa Saadoon', pos: 'defensa' },
    { name: 'Frans Putros', pos: 'defensa' },
  ]},
  { id: 'japon', name: 'Japón', category: 'sorpresas', code: 'JPN', players: [
    { name: 'Zion Suzuki', pos: 'portero' },
    { name: 'Yukinari Sugawara', pos: 'defensa' },
    { name: 'Shogo Taniguchi', pos: 'defensa' },
    { name: 'Kou Itakura', pos: 'defensa' },
    { name: 'Yuto Nagatomo', pos: 'defensa' },
    { name: 'Wataru Endo', pos: 'medio' },
    { name: 'Ao Tanaka', pos: 'medio' },
    { name: 'Takefusa Kubo', pos: 'medio' },
    { name: 'Keisuke Goto', pos: 'delantero' },
    { name: 'Ritsu Doan', pos: 'medio' },
    { name: 'Daizen Maeda', pos: 'medio' },
    { name: 'Keisuke Osako', pos: 'portero' },
    { name: 'Keito Nakamura', pos: 'medio' },
    { name: 'Junya Ito', pos: 'medio' },
    { name: 'Daichi Kamada', pos: 'medio' },
    { name: 'Tsuyoshi Watanabe', pos: 'defensa' },
    { name: 'Yuito Suzuki', pos: 'medio' },
    { name: 'Ayase Ueda', pos: 'delantero' },
    { name: 'Koki Ogawa', pos: 'delantero' },
    { name: 'Ayumu Seko', pos: 'defensa' },
    { name: 'Hiroki Ito', pos: 'defensa' },
    { name: 'Takehiro Tomiyasu', pos: 'defensa' },
    { name: 'Tomoki Hayakawa', pos: 'portero' },
    { name: 'Kaishu Sano', pos: 'medio' },
    { name: 'Junnosuke Suzuki', pos: 'defensa' },
    { name: 'Kento Shiogai', pos: 'delantero' },
  ]},
  { id: 'jordania', name: 'Jordania', category: 'caca', code: 'JOR', players: [
    { name: 'Yazeed Abulaila', pos: 'portero' },
    { name: 'Mohammad Abuhasheesh', pos: 'defensa' },
    { name: 'Abdallah Nasib', pos: 'defensa' },
    { name: 'Husam Abudahab', pos: 'defensa' },
    { name: 'Yazan Alarab', pos: 'defensa' },
    { name: 'Amer Jamous', pos: 'medio' },
    { name: 'Mohammad Abuzraiq', pos: 'delantero' },
    { name: 'Noor Alrawabdeh', pos: 'medio' },
    { name: 'Ali Olwan', pos: 'delantero' },
    { name: 'Mousa Altamari', pos: 'delantero' },
    { name: 'Odeh Fakhoury', pos: 'delantero' },
    { name: 'Nour Baniateyah', pos: 'portero' },
    { name: 'Mahmoud Almardi', pos: 'delantero' },
    { name: 'Rajaei Ayed', pos: 'medio' },
    { name: 'Ibrahim Sadeh', pos: 'medio' },
    { name: 'Mohammad Abualnadi', pos: 'defensa' },
    { name: 'Saleem Obaid', pos: 'defensa' },
    { name: 'Ibrahim Sabra', pos: 'delantero' },
    { name: 'Saed Alrosan', pos: 'defensa' },
    { name: 'Mohannad Abutaha', pos: 'medio' },
    { name: 'Nizar Alrashdan', pos: 'medio' },
    { name: 'Abdallah Alfakhori', pos: 'portero' },
    { name: 'Ehsan Haddad', pos: 'defensa' },
    { name: 'Ali Azaizeh', pos: 'delantero' },
    { name: 'Mohammad Aldaoud', pos: 'medio' },
    { name: 'Anas Badawi', pos: 'defensa' },
  ]},
  { id: 'corea-sur', name: 'Corea del Sur', category: 'sorpresas', code: 'KOR', players: [
    { name: 'Seunggyu Kim', pos: 'portero' },
    { name: 'Hanbeom Lee', pos: 'defensa' },
    { name: 'Gihyuk Lee', pos: 'medio' },
    { name: 'Minjae Kim', pos: 'defensa' },
    { name: 'Taehyeon Kim', pos: 'defensa' },
    { name: 'Inbeom Hwang', pos: 'medio' },
    { name: 'Heungmin Son', pos: 'delantero' },
    { name: 'Seungho Paik', pos: 'medio' },
    { name: 'Guesung Cho', pos: 'delantero' },
    { name: 'Jaesung Lee', pos: 'medio' },
    { name: 'Heechan Hwang', pos: 'medio' },
    { name: 'Bumkeun Song', pos: 'portero' },
    { name: 'Taeseok Lee', pos: 'defensa' },
    { name: 'Wije Cho', pos: 'defensa' },
    { name: 'Moonhwan Kim', pos: 'defensa' },
    { name: 'Jinseob Park', pos: 'defensa' },
    { name: 'Junho Bae', pos: 'medio' },
    { name: 'Hyeongyu Oh', pos: 'delantero' },
    { name: 'Kangin Lee', pos: 'medio' },
    { name: 'Hyunjun Yang', pos: 'medio' },
    { name: 'Hyeonwoo Jo', pos: 'portero' },
    { name: 'Youngwoo Seol', pos: 'defensa' },
    { name: 'Jens Castrop', pos: 'defensa' },
    { name: 'Jingyu Kim', pos: 'medio' },
    { name: 'Jisung Eom', pos: 'medio' },
    { name: 'Donggyeong Lee', pos: 'medio' },
  ]},
  { id: 'mexico', name: 'México', category: 'sorpresas', code: 'MEX', players: [
    { name: 'Raul Rangel', pos: 'portero' },
    { name: 'Jorge Sanchez', pos: 'defensa' },
    { name: 'Cesar Montes', pos: 'defensa' },
    { name: 'Edson Alvarez', pos: 'defensa' },
    { name: 'Johan Vasquez', pos: 'defensa' },
    { name: 'Erik Lira', pos: 'medio' },
    { name: 'Luis Romo', pos: 'medio' },
    { name: 'Alvaro Fidalgo', pos: 'medio' },
    { name: 'Raul Jimenez', pos: 'delantero' },
    { name: 'Alexis Vega', pos: 'delantero' },
    { name: 'Santiago Gimenez', pos: 'delantero' },
    { name: 'Carlos Acevedo', pos: 'portero' },
    { name: 'Guillermo Ochoa', pos: 'portero' },
    { name: 'Armando Gonzalez', pos: 'delantero' },
    { name: 'Israel Reyes', pos: 'defensa' },
    { name: 'Julian Quinones', pos: 'delantero' },
    { name: 'Orbelin Pineda', pos: 'medio' },
    { name: 'Obed Vargas', pos: 'medio' },
    { name: 'Gilberto Mora', pos: 'medio' },
    { name: 'Mateo Chavez', pos: 'defensa' },
    { name: 'Cesar Huerta', pos: 'delantero' },
    { name: 'Guillermo Martinez', pos: 'delantero' },
    { name: 'Jesus Gallardo', pos: 'defensa' },
    { name: 'Luis Chavez', pos: 'medio' },
    { name: 'Roberto Alvarado', pos: 'delantero' },
    { name: 'Brian Gutierrez', pos: 'medio' },
  ]},
  { id: 'marruecos', name: 'Marruecos', category: 'favoritos', code: 'MAR', players: [
    { name: 'Yassine Bounou', pos: 'portero' },
    { name: 'Achraf Hakimi', pos: 'defensa' },
    { name: 'Noussair Mazraoui', pos: 'defensa' },
    { name: 'Sofyan Amrabat', pos: 'medio' },
    { name: 'Nayef Aguerd', pos: 'defensa' },
    { name: 'Ayyoub Bouaddi', pos: 'medio' },
    { name: 'Chemsdine Talbi', pos: 'medio' },
    { name: 'Azzedine Ounahi', pos: 'medio' },
    { name: 'Souane Rahimi', pos: 'delantero' },
    { name: 'Brahim Diaz', pos: 'delantero' },
    { name: 'Ismael Saibari', pos: 'medio' },
    { name: 'Munir El Kajoui', pos: 'portero' },
    { name: 'Zakaria El Ouahdi', pos: 'defensa' },
    { name: 'Issa Diop', pos: 'defensa' },
    { name: 'Samir El Mourabet', pos: 'medio' },
    { name: 'Gessime Yassine', pos: 'medio' },
    { name: 'Abde Ezzalzouli', pos: 'delantero' },
    { name: 'Chadi Riad', pos: 'defensa' },
    { name: 'Youssef Belammari', pos: 'defensa' },
    { name: 'Ayoub El Kaabi', pos: 'delantero' },
    { name: 'Ayoub Amaimouni', pos: 'delantero' },
    { name: 'Yassine', pos: 'portero' },
    { name: 'Achraf', pos: 'medio' },
    { name: 'Noussair', pos: 'medio' },
    { name: 'Sofyan', pos: 'defensa' },
    { name: 'Nayef', pos: 'defensa' },
  ]},
  { id: 'paises-bajos', name: 'Países Bajos', category: 'favoritos', code: 'NED', players: [
    { name: 'Bart Verbruggen', pos: 'portero' },
    { name: 'Jurrien Timber', pos: 'defensa' },
    { name: 'Marten De Roon', pos: 'medio' },
    { name: 'Virgil Van Dijk', pos: 'defensa' },
    { name: 'Nathan Ake', pos: 'defensa' },
    { name: 'Jan-Paul Van Hecke', pos: 'defensa' },
    { name: 'Justin Kluivert', pos: 'medio' },
    { name: 'Ryan Gravenberch', pos: 'medio' },
    { name: 'Wout Weghorst', pos: 'delantero' },
    { name: 'Memphis Depay', pos: 'delantero' },
    { name: 'Cody Gakpo', pos: 'delantero' },
    { name: 'Mats Wieffer', pos: 'defensa' },
    { name: 'Robin Roefs', pos: 'portero' },
    { name: 'Tijjani Reijnders', pos: 'medio' },
    { name: 'Micky Van De Ven', pos: 'defensa' },
    { name: 'Guus Til', pos: 'medio' },
    { name: 'Noa Lang', pos: 'delantero' },
    { name: 'Donyell Malen', pos: 'delantero' },
    { name: 'Brian Brobbey', pos: 'delantero' },
    { name: 'Teun Koopmeiners', pos: 'medio' },
    { name: 'Frenkie De Jong', pos: 'medio' },
    { name: 'Denzel Dumfries', pos: 'defensa' },
    { name: 'Mark Flekken', pos: 'portero' },
    { name: 'Bart', pos: 'delantero' },
    { name: 'Jurriën David Norman', pos: 'defensa' },
    { name: 'Marten Elco', pos: 'medio' },
  ]},
  { id: 'nueva-zelanda', name: 'Nueva Zelanda', category: 'caca', code: 'NZL', players: [
    { name: 'Max Crocombe', pos: 'portero' },
    { name: 'Tim Payne', pos: 'defensa' },
    { name: 'Francis De Vries', pos: 'defensa' },
    { name: 'Tyler Bindon', pos: 'defensa' },
    { name: 'Michael Boxall', pos: 'defensa' },
    { name: 'Joe Bell', pos: 'medio' },
    { name: 'Matthew Garbett', pos: 'medio' },
    { name: 'Marko Stamenic', pos: 'medio' },
    { name: 'Chris Wood', pos: 'delantero' },
    { name: 'Sarpreet Singh', pos: 'medio' },
    { name: 'Elijah Just', pos: 'medio' },
    { name: 'Alex Paulsen', pos: 'portero' },
    { name: 'Liberato Cacace', pos: 'defensa' },
    { name: 'Alex Rufer', pos: 'medio' },
    { name: 'Nando Pijnaker', pos: 'defensa' },
    { name: 'Finn Surman', pos: 'defensa' },
    { name: 'Kosta Barbarouses', pos: 'delantero' },
    { name: 'Ben Waine', pos: 'delantero' },
    { name: 'Ben Old', pos: 'medio' },
    { name: 'Mccowatt Callum', pos: 'medio' },
    { name: 'Jesse Randall', pos: 'delantero' },
    { name: 'Michael Woud', pos: 'portero' },
    { name: 'Ryan Thomas', pos: 'medio' },
    { name: 'Callan Elliot', pos: 'defensa' },
    { name: 'Lachlan Bayliss', pos: 'medio' },
    { name: 'Tommy Smith', pos: 'defensa' },
  ]},
  { id: 'noruega', name: 'Noruega', category: 'sorpresas', code: 'NOR', players: [
    { name: 'Orjan Nyland', pos: 'portero' },
    { name: 'Morten Thorsby', pos: 'medio' },
    { name: 'Kristoffer Ajer', pos: 'defensa' },
    { name: 'Leo Ostigard', pos: 'defensa' },
    { name: 'David Moller Wolfe', pos: 'defensa' },
    { name: 'Patrick Berg', pos: 'medio' },
    { name: 'Alexander Sorloth', pos: 'delantero' },
    { name: 'Sander Berge', pos: 'medio' },
    { name: 'Erling Haaland', pos: 'delantero' },
    { name: 'Martin Odegaard', pos: 'medio' },
    { name: 'Jorgen Strand Larsen', pos: 'delantero' },
    { name: 'Sander Tangvik', pos: 'portero' },
    { name: 'Egil Selvik', pos: 'portero' },
    { name: 'Fredrik Aursnes', pos: 'medio' },
    { name: 'Fredrik Andre Bjorkan', pos: 'defensa' },
    { name: 'Marcus Holmgren Pedersen', pos: 'defensa' },
    { name: 'Torbjorn Heggem', pos: 'defensa' },
    { name: 'Kristian Thorstvedt', pos: 'medio' },
    { name: 'Thelo Aasgaard', pos: 'medio' },
    { name: 'Antonio Nusa', pos: 'delantero' },
    { name: 'Andreas Schjelderup', pos: 'medio' },
    { name: 'Oscar Bobb', pos: 'medio' },
    { name: 'Jens Petter Hauge', pos: 'medio' },
    { name: 'Sondre Langas', pos: 'defensa' },
    { name: 'Henrik Falchener', pos: 'defensa' },
    { name: 'Julian Ryerson', pos: 'delantero' },
  ]},
  { id: 'panama', name: 'Panamá', category: 'petardazos', code: 'PAN', players: [
    { name: 'Luis Mejia', pos: 'portero' },
    { name: 'Cesar Blackman', pos: 'defensa' },
    { name: 'Jose Cordoba', pos: 'defensa' },
    { name: 'Fidel Escobar', pos: 'defensa' },
    { name: 'Edgardo Farina', pos: 'defensa' },
    { name: 'Cristian Martinez', pos: 'medio' },
    { name: 'Jose Luis Rodriguez', pos: 'medio' },
    { name: 'Adalberto Carrasquilla', pos: 'medio' },
    { name: 'Tomas Rodriguez', pos: 'delantero' },
    { name: 'Ismael Diaz', pos: 'medio' },
    { name: 'Edgar Yoel Barcenas', pos: 'medio' },
    { name: 'Cesar Samudio', pos: 'portero' },
    { name: 'Jiovany Ramos', pos: 'defensa' },
    { name: 'Carlos Harvey', pos: 'defensa' },
    { name: 'Eric Davis', pos: 'defensa' },
    { name: 'Andres Andrade', pos: 'defensa' },
    { name: 'Jose Fajardo', pos: 'delantero' },
    { name: 'Cecilio Waterman', pos: 'delantero' },
    { name: 'Alberto Quintero', pos: 'medio' },
    { name: 'Anibal Godoy', pos: 'medio' },
    { name: 'Cesar Yanis', pos: 'medio' },
    { name: 'Orlando Mosquera', pos: 'portero' },
    { name: 'Amir Murillo', pos: 'defensa' },
    { name: 'Azarias Londono', pos: 'delantero' },
    { name: 'Roderick Miller', pos: 'defensa' },
    { name: 'Jorge Gutierrez', pos: 'defensa' },
  ]},
  { id: 'paraguay', name: 'Paraguay', category: 'petardazos', code: 'PAR', players: [
    { name: 'Gatito Fernandez', pos: 'portero' },
    { name: 'Gustavo Velazquez', pos: 'defensa' },
    { name: 'Omar Alderete', pos: 'defensa' },
    { name: 'Juan Jose Caceres', pos: 'defensa' },
    { name: 'Fabian Balbuena', pos: 'defensa' },
    { name: 'Junior Alonso', pos: 'defensa' },
    { name: 'Ramon Sosa', pos: 'medio' },
    { name: 'Diego Gomez', pos: 'medio' },
    { name: 'Antonio Sanabria', pos: 'delantero' },
    { name: 'Miguel Almiron', pos: 'medio' },
    { name: 'Mauricio', pos: 'medio' },
    { name: 'Orlando Gill', pos: 'portero' },
    { name: 'Jose Canale', pos: 'defensa' },
    { name: 'Andres Cubas', pos: 'medio' },
    { name: 'Gustavo Gomez', pos: 'defensa' },
    { name: 'Damian Bobadilla', pos: 'medio' },
    { name: 'Roberto Junior', pos: 'delantero' },
    { name: 'Víctor Gustavo', pos: 'delantero' },
    { name: 'Omar Federico', pos: 'delantero' },
    { name: 'Juan Jose', pos: 'medio' },
    { name: 'Fabián Cornelio', pos: 'delantero' },
    { name: 'Júnior Osmar Ignacio', pos: 'portero' },
    { name: 'Ramón', pos: 'medio' },
    { name: 'Diego Alexander', pos: 'medio' },
    { name: 'Arnaldo Antonio', pos: 'delantero' },
    { name: 'Miguel Angel', pos: 'defensa' },
  ]},
  { id: 'portugal', name: 'Portugal', category: 'favoritos', code: 'POR', players: [
    { name: 'Diogo Costa', pos: 'portero' },
    { name: 'Nelson Semedo', pos: 'defensa' },
    { name: 'Ruben Dias', pos: 'defensa' },
    { name: 'Tomas Araujo', pos: 'defensa' },
    { name: 'Diogo Dalot', pos: 'defensa' },
    { name: 'Matheus Nunes', pos: 'medio' },
    { name: 'Cristiano Ronaldo', pos: 'delantero' },
    { name: 'Bruno Fernandes', pos: 'medio' },
    { name: 'Goncalo Ramos', pos: 'delantero' },
    { name: 'Bernardo Silva', pos: 'medio' },
    { name: 'Joao Felix', pos: 'delantero' },
    { name: 'Jose Sa', pos: 'portero' },
    { name: 'Renato Veiga', pos: 'defensa' },
    { name: 'Goncalo Inacio', pos: 'defensa' },
    { name: 'Joao Neves', pos: 'medio' },
    { name: 'Francisco Trincao', pos: 'delantero' },
    { name: 'Rafael Leao', pos: 'delantero' },
    { name: 'Pedro Neto', pos: 'delantero' },
    { name: 'Goncalo Guedes', pos: 'delantero' },
    { name: 'Joao Cancelo', pos: 'defensa' },
    { name: 'Ruben Neves', pos: 'medio' },
    { name: 'Rui Silva', pos: 'portero' },
    { name: 'Vitinha', pos: 'medio' },
    { name: 'Samu Costa', pos: 'defensa' },
    { name: 'Nuno Mendes', pos: 'defensa' },
    { name: 'Francisco Conceicao', pos: 'delantero' },
  ]},
  { id: 'catar', name: 'Catar', category: 'petardazos', code: 'QAT', players: [
    { name: 'Mahmoud Abunada', pos: 'portero' },
    { name: 'Mahmoud Ibrahim M', pos: 'defensa' },
    { name: 'Pedro Miguel', pos: 'defensa' },
    { name: 'Lucas Mendes', pos: 'defensa' },
    { name: 'Issa Laye', pos: 'defensa' },
    { name: 'Jassem Gaber', pos: 'medio' },
    { name: 'Abdulaziz Hatem', pos: 'delantero' },
    { name: 'Ahmed Alaaeldin', pos: 'delantero' },
    { name: 'Edmilson Junior', pos: 'delantero' },
    { name: 'Mohammed Muntari', pos: 'delantero' },
    { name: 'Hassan Alhaydos', pos: 'delantero' },
    { name: 'Akram Afif', pos: 'medio' },
    { name: 'Karim Boudiaf', pos: 'defensa' },
    { name: 'Ayoub Aloui', pos: 'defensa' },
    { name: 'Homam Ahmed', pos: 'delantero' },
    { name: 'Yusuf Abdurisag', pos: 'defensa' },
    { name: 'Boualem Khoukhi', pos: 'medio' },
    { name: 'Ahmed Alganehi', pos: 'defensa' },
    { name: 'Sultan Albrake', pos: 'delantero' },
    { name: 'Almoez Ali', pos: 'medio' },
    { name: 'Ahmed Fathy', pos: 'portero' },
    { name: 'Salah Zakaria', pos: 'portero' },
    { name: 'Meshaal Barsham', pos: 'medio' },
    { name: 'Assim Madibo', pos: 'delantero' },
    { name: 'Tahsin Jamshid', pos: 'defensa' },
    { name: 'Alhashmi Alhussein', pos: 'delantero' },
  ]},
  { id: 'arabia-saudita', name: 'Arabia Saudita', category: 'caca', code: 'KSA', players: [
    { name: 'Nawaf Alaqidi', pos: 'portero' },
    { name: 'Ali Majrashi', pos: 'defensa' },
    { name: 'Ali Lajami', pos: 'defensa' },
    { name: 'Abdulelah Alamri', pos: 'defensa' },
    { name: 'Hassan Altambakti', pos: 'defensa' },
    { name: 'Nasser Aldawsari', pos: 'medio' },
    { name: 'Musab Aljuwayr', pos: 'medio' },
    { name: 'Aiman Yahya', pos: 'delantero' },
    { name: 'Feras Albrikan', pos: 'delantero' },
    { name: 'Salem Aldawsari', pos: 'delantero' },
    { name: 'Saleh Alshehri', pos: 'delantero' },
    { name: 'Saud Abdulhamid', pos: 'defensa' },
    { name: 'Nawaf Bu Washl', pos: 'defensa' },
    { name: 'Hassan Kadish', pos: 'defensa' },
    { name: 'Abdullah Alkhaibari', pos: 'medio' },
    { name: 'Ziyad Aljohani', pos: 'medio' },
    { name: 'Khalid Alghannam', pos: 'delantero' },
    { name: 'Ala Alhajji', pos: 'medio' },
    { name: 'Abdullah Alhamddan', pos: 'delantero' },
    { name: 'Sultan Mandash', pos: 'delantero' },
    { name: 'Mohammed Alowais', pos: 'portero' },
    { name: 'Ahmed Alkassar', pos: 'portero' },
    { name: 'Mohamed Kanno', pos: 'medio' },
    { name: 'Moteb Alharbi', pos: 'defensa' },
    { name: 'Jehad Thikri', pos: 'defensa' },
    { name: 'Nawaf Dhahi F', pos: 'defensa' },
  ]},
  { id: 'escocia', name: 'Escocia', category: 'petardazos', code: 'SCO', players: [
    { name: 'Angus Gunn', pos: 'portero' },
    { name: 'Aaron Hickey', pos: 'defensa' },
    { name: 'Andy Robertson', pos: 'defensa' },
    { name: 'Mctominay Scott', pos: 'medio' },
    { name: 'Grant Hanley', pos: 'defensa' },
    { name: 'Kieran Tierney', pos: 'defensa' },
    { name: 'Mcginn John', pos: 'medio' },
    { name: 'Tyler Fletcher', pos: 'medio' },
    { name: 'Lyndon Dykes', pos: 'delantero' },
    { name: 'Che Adams', pos: 'delantero' },
    { name: 'Ryan Christie', pos: 'medio' },
    { name: 'Liam Kelly', pos: 'portero' },
    { name: 'Jack Hendry', pos: 'defensa' },
    { name: 'Ross Stewart', pos: 'delantero' },
    { name: 'John Souttar', pos: 'defensa' },
    { name: 'Dominic Hyam', pos: 'defensa' },
    { name: 'Ben Gannon-Doak', pos: 'delantero' },
    { name: 'George Hirst', pos: 'delantero' },
    { name: 'Lewis Ferguson', pos: 'medio' },
    { name: 'Lawrence Shankland', pos: 'delantero' },
    { name: 'Craig Gordon', pos: 'portero' },
    { name: 'Nathan Patterson', pos: 'defensa' },
    { name: 'Mclean Kenny', pos: 'medio' },
    { name: 'Anthony Ralston', pos: 'defensa' },
    { name: 'Findlay Curtis', pos: 'delantero' },
    { name: 'Mckenna Scott', pos: 'defensa' },
  ]},
  { id: 'senegal', name: 'Senegal', category: 'sorpresas', code: 'SEN', players: [
    { name: 'Yehvann Diouf', pos: 'portero' },
    { name: 'Mamadou Sarr', pos: 'defensa' },
    { name: 'Kalidou Koulibaly', pos: 'defensa' },
    { name: 'Abdoulaye Seck', pos: 'defensa' },
    { name: 'Idrissa Gana Gueye', pos: 'medio' },
    { name: 'Pathe Ciss', pos: 'medio' },
    { name: 'Assane Diao', pos: 'delantero' },
    { name: 'Lamine Camara', pos: 'medio' },
    { name: 'Bamba Dieng', pos: 'delantero' },
    { name: 'Sadio Mane', pos: 'delantero' },
    { name: 'Nicolas Jackson', pos: 'delantero' },
    { name: 'Cherif Ndiaye', pos: 'delantero' },
    { name: 'Iliman Ndiaye', pos: 'delantero' },
    { name: 'Ismail Jakobs', pos: 'defensa' },
    { name: 'Krepin Diatta', pos: 'defensa' },
    { name: 'Edouard Mendy', pos: 'portero' },
    { name: 'Pape Matar Sarr', pos: 'medio' },
    { name: 'Ismaila Sarr', pos: 'delantero' },
    { name: 'Moussa Niakhate', pos: 'defensa' },
    { name: 'Ibrahim Mbaye', pos: 'delantero' },
    { name: 'Habib Diarra', pos: 'medio' },
    { name: 'Bara Sapoko Ndiaye', pos: 'medio' },
    { name: 'Mory Diaw', pos: 'portero' },
    { name: 'Antoine Mendy', pos: 'defensa' },
    { name: 'El Hadji Malick Diouf', pos: 'defensa' },
    { name: 'Pape Gueye', pos: 'medio' },
  ]},
  { id: 'sudafrica', name: 'Sudáfrica', category: 'petardazos', code: 'RSA', players: [
    { name: 'Ronwen Williams', pos: 'portero' },
    { name: 'Thabang Matuludi', pos: 'defensa' },
    { name: 'Khulumani Ndamane', pos: 'defensa' },
    { name: 'Teboho Mokoena', pos: 'medio' },
    { name: 'Thalente Mbatha', pos: 'medio' },
    { name: 'Aubrey Modiba', pos: 'defensa' },
    { name: 'Oswin Appollis', pos: 'delantero' },
    { name: 'Tshepang Moremi', pos: 'delantero' },
    { name: 'Lyle Foster', pos: 'delantero' },
    { name: 'Relebohile Mofokeng', pos: 'delantero' },
    { name: 'Themba Zwane', pos: 'medio' },
    { name: 'Thapelo Maseko', pos: 'delantero' },
    { name: 'Sphephelo Sithole', pos: 'medio' },
    { name: 'Mbekezeli Mbokazi', pos: 'defensa' },
    { name: 'Iqraam Rayners', pos: 'delantero' },
    { name: 'Sipho Chaine', pos: 'portero' },
    { name: 'Evidence Makgopa', pos: 'delantero' },
    { name: 'Samukelo Kabini', pos: 'defensa' },
    { name: 'Nkosinathi Sibisi', pos: 'defensa' },
    { name: 'Khuliso Mudau', pos: 'defensa' },
    { name: 'Ime Okon', pos: 'defensa' },
    { name: 'Ricardo Goss', pos: 'portero' },
    { name: 'Jayden Adams', pos: 'medio' },
    { name: 'Olwethu Makhanya', pos: 'defensa' },
    { name: 'Kamogelo Sebelebele', pos: 'delantero' },
    { name: 'Bradley Cross', pos: 'defensa' },
  ]},
  { id: 'espana', name: 'España', category: 'favoritos', code: 'ESP', players: [
    { name: 'David Raya', pos: 'portero' },
    { name: 'Marc Pubill', pos: 'defensa' },
    { name: 'Alex Grimaldo', pos: 'defensa' },
    { name: 'Eric Garcia', pos: 'defensa' },
    { name: 'Marcos Llorente', pos: 'defensa' },
    { name: 'Mikel Merino', pos: 'medio' },
    { name: 'Ferran Torres', pos: 'delantero' },
    { name: 'Fabian Ruiz', pos: 'medio' },
    { name: 'Gavi', pos: 'medio' },
    { name: 'Dani Olmo', pos: 'delantero' },
    { name: 'Yeremy Pino', pos: 'delantero' },
    { name: 'Pedro Porro', pos: 'defensa' },
    { name: 'Joan Garcia', pos: 'portero' },
    { name: 'Aymeric Laporte', pos: 'defensa' },
    { name: 'Alex Baena', pos: 'medio' },
    { name: 'Rodri', pos: 'medio' },
    { name: 'Nico Williams', pos: 'delantero' },
    { name: 'Martin Zubimendi', pos: 'medio' },
    { name: 'Lamine Yamal', pos: 'delantero' },
    { name: 'Pedri', pos: 'medio' },
    { name: 'Mikel Oyarzabal', pos: 'delantero' },
    { name: 'Pau Cubarsi', pos: 'defensa' },
    { name: 'Unai Simon', pos: 'portero' },
    { name: 'Marc Cucurella', pos: 'defensa' },
    { name: 'Victor Munoz', pos: 'delantero' },
    { name: 'Borja Iglesias', pos: 'delantero' },
  ]},
  { id: 'suecia', name: 'Suecia', category: 'petardazos', code: 'SWE', players: [
    { name: 'Jacob Widell Zetterstrom', pos: 'portero' },
    { name: 'Gustaf Lagerbielke', pos: 'defensa' },
    { name: 'Victor Lindelof', pos: 'defensa' },
    { name: 'Isak Hien', pos: 'defensa' },
    { name: 'Gabriel Gudmundsson', pos: 'defensa' },
    { name: 'Herman Johansson', pos: 'defensa' },
    { name: 'Lucas Bergvall', pos: 'medio' },
    { name: 'Daniel Svensson', pos: 'defensa' },
    { name: 'Alexander Isak', pos: 'delantero' },
    { name: 'Benjamin Nygren', pos: 'medio' },
    { name: 'Anthony Elanga', pos: 'delantero' },
    { name: 'Viktor Johansson', pos: 'portero' },
    { name: 'Ken Sema', pos: 'medio' },
    { name: 'Hjalmar Ekdal', pos: 'defensa' },
    { name: 'Carl Starfelt', pos: 'defensa' },
    { name: 'Jesper Karlstrom', pos: 'medio' },
    { name: 'Viktor Gyokeres', pos: 'delantero' },
    { name: 'Yasin Ayari', pos: 'medio' },
    { name: 'Mattias Svanberg', pos: 'medio' },
    { name: 'Eric Smith', pos: 'defensa' },
    { name: 'Alexander Bernhardsson', pos: 'defensa' },
    { name: 'Besfort Zeneli', pos: 'medio' },
    { name: 'Kristoffer Nordfeldt', pos: 'portero' },
    { name: 'Elliot Stroud', pos: 'defensa' },
    { name: 'Gustaf Nilsson', pos: 'delantero' },
    { name: 'Taha Ali', pos: 'delantero' },
  ]},
  { id: 'suiza', name: 'Suiza', category: 'sorpresas', code: 'SUI', players: [
    { name: 'Gregor Kobel', pos: 'portero' },
    { name: 'Miro Muheim', pos: 'defensa' },
    { name: 'Silvan Widmer', pos: 'defensa' },
    { name: 'Nico Elvedi', pos: 'defensa' },
    { name: 'Manuel Akanji', pos: 'defensa' },
    { name: 'Denis Zakaria', pos: 'medio' },
    { name: 'Breel Embolo', pos: 'delantero' },
    { name: 'Remo Freuler', pos: 'medio' },
    { name: 'Johan Manzambi', pos: 'medio' },
    { name: 'Granit Xhaka', pos: 'medio' },
    { name: 'Dan Ndoye', pos: 'delantero' },
    { name: 'Yvon Mvogo', pos: 'portero' },
    { name: 'Ricardo Rodriguez', pos: 'defensa' },
    { name: 'Ardon Jashari', pos: 'medio' },
    { name: 'Djibril Sow', pos: 'medio' },
    { name: 'Christian Fassnacht', pos: 'delantero' },
    { name: 'Ruben Vargas', pos: 'delantero' },
    { name: 'Eray Coemert', pos: 'defensa' },
    { name: 'Noah Okafor', pos: 'delantero' },
    { name: 'Michel Aebischer', pos: 'medio' },
    { name: 'Marvin Keller', pos: 'portero' },
    { name: 'Fabian Rieder', pos: 'medio' },
    { name: 'Zeki Amdouni', pos: 'delantero' },
    { name: 'Aurele Amenda', pos: 'defensa' },
    { name: 'Luca Jaquez', pos: 'defensa' },
    { name: 'Cedric Itten', pos: 'delantero' },
  ]},
  { id: 'tunez', name: 'Túnez', category: 'petardazos', code: 'TUN', players: [
    { name: 'Mouhib Chamakh', pos: 'portero' },
    { name: 'Ali Abdi', pos: 'defensa' },
    { name: 'Montassar Talbi', pos: 'defensa' },
    { name: 'Omar Rekik', pos: 'defensa' },
    { name: 'Adam Arous', pos: 'defensa' },
    { name: 'Dylan Bronn', pos: 'defensa' },
    { name: 'Elias Achouri', pos: 'delantero' },
    { name: 'Elias Saad', pos: 'delantero' },
    { name: 'Hazem Mastouri', pos: 'delantero' },
    { name: 'Hannibal Mejbri', pos: 'medio' },
    { name: 'Ismael Gharbi', pos: 'medio' },
    { name: 'Mortadha Ben Ouanes', pos: 'defensa' },
    { name: 'Rani Khedira', pos: 'medio' },
    { name: 'Khalil Ayari', pos: 'medio' },
    { name: 'Mohamed Hadj Mahmoud', pos: 'medio' },
    { name: 'Aymen Dahmen', pos: 'portero' },
    { name: 'Ellyes Skhiri', pos: 'medio' },
    { name: 'Rayan Elloumi', pos: 'delantero' },
    { name: 'Firas Chaouat', pos: 'delantero' },
    { name: 'Yan Valery', pos: 'defensa' },
    { name: 'Abdelmouhib', pos: 'defensa' },
    { name: 'Ali', pos: 'portero' },
    { name: 'Montassar Omar', pos: 'defensa' },
    { name: 'Omar', pos: 'defensa' },
    { name: 'Adam', pos: 'medio' },
    { name: 'Dylan Daniel Mahmoud', pos: 'medio' },
  ]},
  { id: 'turquia', name: 'Turquía', category: 'sorpresas', code: 'TUR', players: [
    { name: 'Arda Guler', pos: 'portero' },
    { name: 'Deniz Gul', pos: 'defensa' },
    { name: 'Hakan Calhanoglu', pos: 'defensa' },
    { name: 'Kenan Yildiz', pos: 'defensa' },
    { name: 'Altay Bayindir', pos: 'medio' },
    { name: 'Eren Elmali', pos: 'medio' },
    { name: 'Abdulkerim Bardakci', pos: 'delantero' },
    { name: 'Ozan Kabak', pos: 'delantero' },
    { name: 'Ismail Yuksek', pos: 'delantero' },
    { name: 'Irfan Can Kahveci', pos: 'medio' },
    { name: 'Mert Muldur', pos: 'delantero' },
    { name: 'Yunus Akgun', pos: 'portero' },
    { name: 'Ferdi Kadioglu', pos: 'defensa' },
    { name: 'Baris Alper Yilmaz', pos: 'defensa' },
    { name: 'Kaan Ayhan', pos: 'defensa' },
    { name: 'Ugurcan Cakir', pos: 'medio' },
    { name: 'Oguz Aydin', pos: 'delantero' },
    { name: 'Samet Akaydin', pos: 'defensa' },
    { name: 'Can Uzun', pos: 'delantero' },
    { name: 'Mert', pos: 'defensa' },
    { name: 'Zeki̇ Çeli̇k', pos: 'delantero' },
    { name: 'Demi̇ral', pos: 'medio' },
    { name: 'Çağlar', pos: 'portero' },
    { name: 'Özcan', pos: 'delantero' },
    { name: 'Orkun Kökçü', pos: 'defensa' },
    { name: 'Aktürkoğlu', pos: 'delantero' },
  ]},
  { id: 'uruguay', name: 'Uruguay', category: 'sorpresas', code: 'URU', players: [
    { name: 'Sergio Rochet', pos: 'portero' },
    { name: 'Jose Maria Gimenez', pos: 'defensa' },
    { name: 'Sebastian Caceres', pos: 'defensa' },
    { name: 'Ronald Araujo', pos: 'defensa' },
    { name: 'Manuel Ugarte', pos: 'medio' },
    { name: 'Rodrigo Bentancur', pos: 'medio' },
    { name: 'Nicolas De La Cruz', pos: 'medio' },
    { name: 'Federico Valverde', pos: 'medio' },
    { name: 'Darwin Nunez', pos: 'delantero' },
    { name: 'Giorgian De Arrascaeta', pos: 'medio' },
    { name: 'Facundo Pellistri', pos: 'delantero' },
    { name: 'Santiago Mele', pos: 'portero' },
    { name: 'Guillermo Varela', pos: 'defensa' },
    { name: 'Agustin Canobbio', pos: 'medio' },
    { name: 'Emiliano Martinez', pos: 'medio' },
    { name: 'Mathias Olivera', pos: 'defensa' },
    { name: 'Matias Vina', pos: 'defensa' },
    { name: 'Brian Rodriguez', pos: 'delantero' },
    { name: 'Rodrigo Aguirre', pos: 'delantero' },
    { name: 'Maxi Araujo', pos: 'medio' },
    { name: 'Federico Vinas', pos: 'delantero' },
    { name: 'Joaquin Piquerez', pos: 'medio' },
    { name: 'Fernando Muslera', pos: 'portero' },
    { name: 'Santiago Bueno', pos: 'defensa' },
    { name: 'Juan Manuel Sanabria', pos: 'medio' },
    { name: 'Rodrigo Zalazar', pos: 'medio' },
  ]},
  { id: 'eeuu', name: 'EE. UU.', category: 'sorpresas', code: 'USA', players: [
    { name: 'Matt Turner', pos: 'portero' },
    { name: 'Sergino Dest', pos: 'defensa' },
    { name: 'Chris Richards', pos: 'defensa' },
    { name: 'Tyler Adams', pos: 'medio' },
    { name: 'Antonee Robinson', pos: 'defensa' },
    { name: 'Auston Trusty', pos: 'defensa' },
    { name: 'Giovanni Reyna', pos: 'medio' },
    { name: 'Mckennie Weston', pos: 'medio' },
    { name: 'Ricardo Pepi', pos: 'delantero' },
    { name: 'Christian Pulisic', pos: 'delantero' },
    { name: 'Brenden Aaronson', pos: 'delantero' },
    { name: 'Miles Robinson', pos: 'defensa' },
    { name: 'Tim Ream', pos: 'defensa' },
    { name: 'Matthew Charles', pos: 'medio' },
    { name: 'Sergiño Gianni', pos: 'medio' },
    { name: 'Christopher Jeffrey', pos: 'defensa' },
    { name: 'Tyler Shaan', pos: 'medio' },
    { name: 'Antonee', pos: 'defensa' },
    { name: 'Auston Levi-Jesaiah', pos: 'delantero' },
    { name: 'Giovanni Alejandro', pos: 'delantero' },
    { name: 'Weston James Earl', pos: 'delantero' },
    { name: 'Ricardo Daniel', pos: 'defensa' },
    { name: 'Christian Mate', pos: 'defensa' },
    { name: 'Brenden Russell', pos: 'portero' },
    { name: 'Miles Gordon', pos: 'portero' },
    { name: 'Timothy Michael', pos: 'delantero' },
  ]},
  { id: 'uzbekistan', name: 'Uzbekistán', category: 'petardazos', code: 'UZB', players: [
    { name: 'Utkir Yusupov', pos: 'portero' },
    { name: 'Abdukodir Khusanov', pos: 'defensa' },
    { name: 'Khojiakbar Alijonov', pos: 'defensa' },
    { name: 'Farrukh Sayfiev', pos: 'defensa' },
    { name: 'Rustam Ashurmatov', pos: 'defensa' },
    { name: 'Akmal Mozgovoy', pos: 'medio' },
    { name: 'Otabek Shukurov', pos: 'medio' },
    { name: 'Jamshid Iskanderov', pos: 'medio' },
    { name: 'Odiljon Xamrobekov', pos: 'medio' },
    { name: 'Jaloliddin Masharipov', pos: 'medio' },
    { name: 'Oston Urunov', pos: 'medio' },
    { name: 'Abduvohid Nematov', pos: 'portero' },
    { name: 'Sherzod Nasrullaev', pos: 'defensa' },
    { name: 'Eldor Shomurodov', pos: 'delantero' },
    { name: 'Umar Eshmurodov', pos: 'defensa' },
    { name: 'Botirali Ergashev', pos: 'portero' },
    { name: 'Dostonbek Khamdamov', pos: 'medio' },
    { name: 'Abdulla Abdullaev', pos: 'defensa' },
    { name: 'Azizjon Ganiev', pos: 'medio' },
    { name: 'Azizbek Amonov', pos: 'delantero' },
    { name: 'Igor Sergeev', pos: 'delantero' },
    { name: 'Abbosbek Fayzullaev', pos: 'medio' },
    { name: 'Sherzod Esanov', pos: 'medio' },
    { name: 'Behruzjon Karimov', pos: 'defensa' },
    { name: 'Avazbek Ulmasaliyev', pos: 'defensa' },
    { name: 'Jakhongir Urozov', pos: 'defensa' },
  ]},
];

// ─── Seed ─────────────────────────────────────────────────────────────────────

export async function runSeedIfEmpty(): Promise<void> {
  const db = getDb();
  const countResult = await db.query('SELECT COUNT(*) as cnt FROM teams');
  const cnt = parseInt(countResult.rows[0].cnt, 10);
  if (cnt > 0) {
    console.log(`✓ Seed: ${cnt} equipos ya existen, omitiendo seed`);
    return;
  }

  const client = await db.connect();
  let teamCount = 0;
  let playerCount = 0;

  try {
    await client.query('BEGIN');
    for (const team of TEAMS) {
      await client.query(
        'INSERT INTO teams(id, name, country_code, category) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING',
        [team.id, team.name, team.code, team.category]
      );
      teamCount++;
      for (const p of team.players) {
        await client.query(
          'INSERT INTO players(id, name, team_id, position) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING',
          [uuid(), p.name, team.id, p.pos]
        );
        playerCount++;
      }
    }
    await client.query('COMMIT');
  } catch (err) {
    await client.query('ROLLBACK');
    throw err;
  } finally {
    client.release();
  }

  console.log(`✓ Seed: ${teamCount} equipos insertados`);
  console.log(`✓ Seed: ${playerCount} jugadores insertados`);
}

// Ejecutable directo: ts-node src/scripts/seed.ts
if (require.main === module) {
  runMigrations().then(() => runSeedIfEmpty()).then(() => process.exit(0)).catch(console.error);
}
